# Generated by Django 4.2.8 on 2024-01-21 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_album_options_alter_review_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='image',
            field=models.ImageField(default='album_default.jpg', upload_to='album_pics'),
        ),
    ]
